In [1]:
import torch

In [2]:
img_t = torch.randn(3, 5, 5)  # 각각이 [채널 크기, 행 크기, 열 크기]가 됨
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [3]:
batch_t = torch.randn(2, 3, 5, 5)  # [배치 크기, 채널 크기, 행 크기, 열 크기]

In [4]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [5]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [6]:
img_weights = (img_t * unsqueezed_weights)
img_weights

tensor([[[-0.4777, -0.0053,  0.2987, -0.1467, -0.0563],
         [-0.2558,  0.3977, -0.1337,  0.3117, -0.3055],
         [-0.1456, -0.1414,  0.1915, -0.0980,  0.2722],
         [ 0.4058,  0.1802,  0.1105, -0.2892,  0.1825],
         [-0.0748, -0.0187,  0.2169, -0.4363,  0.2415]],

        [[ 1.3768, -0.3500,  0.9587,  0.1935,  0.7923],
         [ 0.3221,  0.4180, -0.8975, -0.6412,  0.7276],
         [-1.0772, -0.4126, -0.6187,  0.4764,  0.1886],
         [-0.5368, -0.0202,  0.7337,  0.4892, -0.1925],
         [ 0.1043, -0.9717, -0.7034,  1.5143,  0.0940]],

        [[ 0.1417,  0.1844, -0.0336, -0.0111, -0.0206],
         [ 0.0211, -0.0446, -0.0026, -0.0989,  0.0738],
         [ 0.0228, -0.0820, -0.0275,  0.0408,  0.1643],
         [ 0.0478,  0.0685, -0.0908,  0.0390, -0.0590],
         [-0.0878,  0.1259,  0.0423, -0.0570, -0.1197]]])

In [7]:
batch_weights = (batch_t * unsqueezed_weights)
batch_weights

tensor([[[[ 2.5874e-01,  3.3589e-02,  4.0759e-01,  1.2574e-01, -5.9185e-02],
          [ 2.0193e-01,  8.0029e-02,  6.7207e-02,  2.4565e-01, -3.3030e-01],
          [ 2.2824e-02,  3.0540e-01, -1.0624e-01,  1.5841e-01,  2.8283e-01],
          [-6.2396e-01,  2.4894e-01,  1.0784e-01, -8.9533e-03,  2.6718e-01],
          [-1.5205e-01,  1.8688e-01,  1.9825e-01,  5.5791e-01, -1.1744e-02]],

         [[ 1.0081e+00, -3.7362e-01, -4.1687e-02, -3.6867e-01, -8.2405e-01],
          [-3.9177e-01, -1.6389e-01, -4.7427e-01, -8.9751e-01,  4.3490e-01],
          [ 9.1952e-01, -2.8920e-01, -2.1512e-01, -6.6707e-01,  9.8013e-01],
          [ 1.5178e+00,  1.1270e+00,  2.5120e-02,  6.4129e-01,  7.6013e-01],
          [-5.3107e-01, -7.6090e-01,  3.1582e-02, -9.6553e-01, -2.0039e-01]],

         [[-1.3698e-02,  1.2300e-01, -1.0740e-01,  3.1620e-02, -1.1203e-01],
          [-3.6357e-02,  3.5404e-02,  7.2948e-03,  2.4733e-02, -1.8443e-02],
          [ 7.2278e-02, -7.9601e-04,  8.2939e-02, -1.3440e-01, -9.4540e-

In [8]:
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [9]:
img_gray_weighted_fancy = torch.einsum('...chw, c -> ...hw', img_t, weights)
img_gray_weighted_fancy, img_gray_weighted_fancy.shape

(tensor([[ 1.0408, -0.1709,  1.2238,  0.0357,  0.7155],
         [ 0.0874,  0.7711, -1.0338, -0.4283,  0.4959],
         [-1.2000, -0.6361, -0.4547,  0.4192,  0.6251],
         [-0.0832,  0.2284,  0.7533,  0.2390, -0.0690],
         [-0.0584, -0.8646, -0.4442,  1.0210,  0.2158]]),
 torch.Size([5, 5]))

In [10]:
batch_gray_weighted_fancy = torch.einsum('...chw, c -> ...hw', batch_t, weights)
batch_gray_weighted_fancy, batch_gray_weighted_fancy.shape

(tensor([[[ 1.2532, -0.2170,  0.2585, -0.2113, -0.9953],
          [-0.2262, -0.0485, -0.3998, -0.6271,  0.0862],
          [ 1.0146,  0.0154, -0.2384, -0.6431,  1.1684],
          [ 0.9309,  1.4315,  0.1175,  0.6007,  0.9677],
          [-0.6692, -0.4892,  0.1958, -0.4334, -0.1855]],
 
         [[-0.5756,  1.3394, -0.6592, -0.5071,  1.2421],
          [-0.0746,  0.0150, -0.3115, -0.4384,  0.1305],
          [-0.2393, -0.4918, -0.7306,  1.2983,  0.2918],
          [-0.7921,  0.8871,  0.4835,  1.2159,  0.4387],
          [-0.6849,  1.0262, -0.6189, -1.5949, -1.3073]]]),
 torch.Size([2, 5, 5]))

In [11]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

/tmp/ipykernel_19943/2371314847.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ../c10/core/TensorImpl.h:1408.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [12]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
img_named

tensor([[[-2.2470, -0.0248,  1.4050, -0.6900, -0.2646],
         [-1.2033,  1.8708, -0.6288,  1.4661, -1.4370],
         [-0.6849, -0.6649,  0.9008, -0.4611,  1.2805],
         [ 1.9086,  0.8474,  0.5196, -1.3601,  0.8586],
         [-0.3521, -0.0881,  1.0202, -2.0521,  1.1357]],

        [[ 1.9251, -0.4894,  1.3405,  0.2705,  1.1078],
         [ 0.4504,  0.5844, -1.2549, -0.8965,  1.0173],
         [-1.5061, -0.5770, -0.8651,  0.6661,  0.2637],
         [-0.7505, -0.0283,  1.0258,  0.6841, -0.2692],
         [ 0.1458, -1.3586, -0.9836,  2.1174,  0.1314]],

        [[ 1.9627,  2.5544, -0.4651, -0.1535, -0.2850],
         [ 0.2925, -0.6175, -0.0359, -1.3692,  1.0226],
         [ 0.3153, -1.1364, -0.3803,  0.5656,  2.2756],
         [ 0.6616,  0.9489, -1.2581,  0.5395, -0.8171],
         [-1.2158,  1.7434,  0.5861, -0.7901, -1.6575]]],
       names=('channels', 'rows', 'columns'))

In [13]:
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named

tensor([[[[ 1.2170e+00,  1.5799e-01,  1.9172e+00,  5.9143e-01, -2.7839e-01],
          [ 9.4983e-01,  3.7643e-01,  3.1612e-01,  1.1555e+00, -1.5536e+00],
          [ 1.0736e-01,  1.4365e+00, -4.9971e-01,  7.4512e-01,  1.3303e+00],
          [-2.9349e+00,  1.1710e+00,  5.0722e-01, -4.2113e-02,  1.2567e+00],
          [-7.1518e-01,  8.7902e-01,  9.3249e-01,  2.6242e+00, -5.5242e-02]],

         [[ 1.4096e+00, -5.2240e-01, -5.8287e-02, -5.1547e-01, -1.1522e+00],
          [-5.4777e-01, -2.2915e-01, -6.6313e-01, -1.2549e+00,  6.0809e-01],
          [ 1.2857e+00, -4.0436e-01, -3.0078e-01, -9.3271e-01,  1.3704e+00],
          [ 2.1221e+00,  1.5758e+00,  3.5123e-02,  8.9666e-01,  1.0628e+00],
          [-7.4255e-01, -1.0639e+00,  4.4158e-02, -1.3500e+00, -2.8019e-01]],

         [[-1.8972e-01,  1.7036e+00, -1.4876e+00,  4.3795e-01, -1.5516e+00],
          [-5.0356e-01,  4.9037e-01,  1.0104e-01,  3.4256e-01, -2.5545e-01],
          [ 1.0011e+00, -1.1025e-02,  1.1487e+00, -1.8615e+00, -1.3094e+

In [14]:
print('img named:', img_named.shape, img_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')


In [15]:
print('batch named:', batch_named.shape, batch_named.names)

batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [16]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [17]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [18]:
weights

tensor([0.2126, 0.7152, 0.0722])

In [19]:
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [20]:
weights_aligned

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]], names=('channels', 'rows', 'columns'))

In [21]:
gray_named = (img_named[..., :3] * weights_named).sum('channels')

RuntimeError: Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.

In [22]:
img_named[..., :3]

tensor([[[-2.2470, -0.0248,  1.4050],
         [-1.2033,  1.8708, -0.6288],
         [-0.6849, -0.6649,  0.9008],
         [ 1.9086,  0.8474,  0.5196],
         [-0.3521, -0.0881,  1.0202]],

        [[ 1.9251, -0.4894,  1.3405],
         [ 0.4504,  0.5844, -1.2549],
         [-1.5061, -0.5770, -0.8651],
         [-0.7505, -0.0283,  1.0258],
         [ 0.1458, -1.3586, -0.9836]],

        [[ 1.9627,  2.5544, -0.4651],
         [ 0.2925, -0.6175, -0.0359],
         [ 0.3153, -1.1364, -0.3803],
         [ 0.6616,  0.9489, -1.2581],
         [-1.2158,  1.7434,  0.5861]]], names=('channels', 'rows', 'columns'))

In [23]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

In [24]:
double_points = torch.ones(10, 2, dtype=torch.double)
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [26]:
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
short_points

tensor([[1, 2],
        [3, 4]], dtype=torch.int16)

In [27]:
short_points.dtype

torch.int16

In [28]:
double_points = torch.zeros(10, 2).double()
double_points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [30]:
short_points = torch.ones(10, 2).short()
short_points

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)

In [31]:
double_points = torch.zeros(10, 2).to(torch.double)
double_points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [32]:
short_points = torch.ones(10, 2).to(torch.short)
short_points

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)

In [33]:
points_64 = torch.rand(5, dtype=torch.double)
points_64

tensor([0.9614, 0.7327, 0.8007, 0.2193, 0.4169], dtype=torch.float64)

In [35]:
points_short = points_64.to(torch.short)
points_short

tensor([0, 0, 0, 0, 0], dtype=torch.int16)

In [36]:
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [37]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a, a_t

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

In [38]:
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [39]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

### 3.7.1 저장 공간 인덱싱

In [41]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [42]:
points_storage = points.storage()
points_storage[0]

4.0

In [43]:
points.storage()[1]

1.0

차원에 무관하게 실제 저장 공간 레이아웃은 1차원

In [44]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

### 3.7.2 저장된 값을 수정하기: 텐서 내부 연산

In [45]:
a = torch.ones(3, 2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [46]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## 3.8 텐서 메타데이터: 사이즈, 오프셋, 스트라이드

### 3.8.1 다른 텐서의 저장 공간에 대한 뷰 만들기

In [47]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [48]:
second_point.size()

torch.Size([2])

In [49]:
second_point

tensor([5., 3.])

In [50]:
second_point.shape

torch.Size([2])

In [51]:
points.stride()

(2, 1)

In [52]:
points[0].storage_offset()

0

In [53]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [54]:
second_point.storage_offset()

2

In [55]:
second_point.stride()

(1,)

In [56]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [58]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

### 3.8.2 복사 없이 텐서 전치하기

In [59]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [60]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [61]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [62]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [65]:
id(points.storage()) == id(points_t.storage())

True

In [63]:
points.stride()

(2, 1)

In [64]:
points_t.stride()

(1, 2)

### 3.8.3 더 높은 차원에서의 전치 연산

In [66]:
some_t = torch.ones(3, 4, 5)
some_t

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [67]:
transpose_t = some_t.transpose(0, 2)
transpose_t

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [68]:
some_t.shape

torch.Size([3, 4, 5])

In [69]:
transpose_t.shape

torch.Size([5, 4, 3])

In [70]:
some_t.stride()

(20, 5, 1)

In [71]:
transpose_t.stride()

(1, 5, 20)

### 3.8.4 인접한 텐서

In [72]:
points.is_contiguous()

True

In [73]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [74]:
points_t.is_contiguous()

False

In [75]:
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [76]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [77]:
pionts_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [78]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [79]:
points_t.stride()

(1, 2)

In [80]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [81]:
points_t_cont.stride()

(3, 1)

In [83]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

## 3.9 텐서를 GPU로 옮기기

### 3.9.1 텐서 디바이스 속성 관리

In [86]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [87]:
points_gpu = points.to(device='cuda')
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [88]:
points_gpu = points.to(device='cuda:0')
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [89]:
points = 2 * points
points

tensor([[ 8.,  2.],
        [10.,  6.],
        [ 4.,  2.]])

In [90]:
points_gpu = 2 * points.to(device='cuda')
points_gpu

tensor([[16.,  4.],
        [20., 12.],
        [ 8.,  4.]], device='cuda:0')

In [91]:
points_gpu  = points_gpu + 4
points_gpu

tensor([[20.,  8.],
        [24., 16.],
        [12.,  8.]], device='cuda:0')

In [92]:
points_cpu = points_gpu.to(device='cpu')
points_cpu

tensor([[20.,  8.],
        [24., 16.],
        [12.,  8.]])

In [93]:
points_gpu = points.cuda()
points_gpu

tensor([[ 8.,  2.],
        [10.,  6.],
        [ 4.,  2.]], device='cuda:0')

In [94]:
points_gpu = points.cuda(1)
points_gpu

tensor([[ 8.,  2.],
        [10.,  6.],
        [ 4.,  2.]], device='cuda:1')

In [96]:
points_cpu = points_gpu.cpu()
points_cpu

tensor([[ 8.,  2.],
        [10.,  6.],
        [ 4.,  2.]])

## 3.10 넘파이 호환

In [97]:
points = torch.ones(3, 4)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [98]:
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [99]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## 3.11 일반화된 텐서도 텐서다

## 3.12 텐서 직렬화

In [100]:
torch.save(points, './ourpoints.t')

In [101]:
with open('./ourpoints.t', 'wb') as f:
    torch.save(points, f)

In [102]:
points = torch.load('./ourpoints.t')
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [103]:
with open('./ourpoints.t', 'rb') as f:
    points = torch.load(f)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### 3.12.1 h5py 로 HDF5 병렬화하기

In [105]:
import h5py

In [106]:
f = h5py.File('./ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [107]:
points.numpy()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [108]:
f = h5py.File('./ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]
dset, last_points

(<HDF5 dataset "coords": shape (3, 4), type "<f4">,
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32))

In [109]:
last_points = torch.from_numpy(dset[-2:])
f.close()

In [110]:
last_points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [111]:
dset

<Closed HDF5 dataset>

### 3.14 연습 문제

### 1. list(range(9)) 로 부터 텐서를 만들어보라. 사이즈, 오프셋, 스트라이드는 얼마일지 계산해보라.

In [112]:
array = list(range(9))
array

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [114]:
a = torch.tensor(array)

In [117]:
a.size()  # [9]

torch.Size([9])

In [115]:
a.storage_offset()  # 0

0

In [116]:
a.stride()  # (1,)

(1,)

#### **a.** b = a.view(3, 3) 으로 텐서를 만들어라. view 의 역할은 무엇인가? a 와 b 가 같은 공간을 가리키고 있는지 확인해보라

In [118]:
b = a.view(3, 3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [119]:
b.size()  # [3, 3]

torch.Size([3, 3])

In [120]:
b.stride()  # (3, 1)

(3, 1)

In [121]:
b.storage_offset() # 0

0

In [122]:
id(a.storage()) == id(b.storage())  # True

True

#### **b.** c = b[1:, 1:] 로 텐서를 만들고 사이즈, 오프셋, 스트라이드는 얼마일지 계산해보라.

In [123]:
c = b[1:, 1:]
c

tensor([[4, 5],
        [7, 8]])

In [125]:
c.size()  # [2, 2]

torch.Size([2, 2])

In [126]:
c.storage_offset()  # 1 틀림 -> 4

4

In [127]:
c.stride()  # (2, 1) 틀림 -> (3, 1)

(3, 1)

### 2. 코사인이나 제곱근 같은 수학 연산을 하나 골라라. 동일한 역할을 하는 함수를 torch 라이브러리에서 찾을 수 있을까?

In [129]:
# 코사인

torch.cos(torch.tensor(1))

tensor(0.5403)

#### **a.** 텐서 a 에 대해 해당 함수를 요소 단위로 실행해보라. 왜 오류가 발생할까?

In [135]:
a = list(range(9))

In [137]:
torch.cos(a[0])

TypeError: cos(): argument 'input' (position 1) must be Tensor, not int

In [138]:
torch.cos(torch.tensor(a[0]))

tensor(1.)