## 5.5 파이토치의 자동미분: 모든 것을 역전파하라

### 5.5.1 기울기 자동 계산

#### 자동미분 적용하기

In [1]:
def model(t_u, w, b):
    return w * t_u + b

In [2]:
def loss_fn(t_p, t_c):
    squared_diffs = (t_p - t_c)**2
    return squared_diffs.mean()

In [3]:
import torch

In [4]:
params = torch.tensor([1.0, 0.0], requires_grad=True)

#### 미분 속성 사용하기

In [5]:
params.grad is None

True

In [6]:
t_c = [0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c = torch.tensor(t_c)
t_u = torch.tensor(t_u)

In [8]:
loss = loss_fn(model(t_u, *params), t_c)
loss.backward()

In [9]:
params.grad

tensor([4517.2969,   82.6000])

#### 미분 함수 누적하기

In [10]:
if params.grad is not None:
    params.grad.zero_()

In [11]:
params.grad

tensor([0., 0.])

In [12]:
def training_loop(n_epochs, learning_rate, params, t_u, t_c):
    for epoch in range(1, n_epochs + 1):
        if params.grad is not None:
            params.grad.zero_()
            
        t_p = model(t_u, *params)
        loss = loss_fn(t_p, t_c)
        loss.backward()
        
        with torch.no_grad():
            params -= learning_rate * params.grad
            
        if epoch % 500 == 0:
            print('Epoch %d, Loss %f' % (epoch, float(loss)))
            
    return params

In [13]:
t_un = 0.1 * t_u

In [14]:
training_loop(
    n_epochs=5000,
    learning_rate=1e-2,
    params=torch.tensor([1.0, 0.0], requires_grad=True),
    t_u=t_un,
    t_c=t_c,
)

Epoch 500, Loss 7.860115
Epoch 1000, Loss 3.828538
Epoch 1500, Loss 3.092191
Epoch 2000, Loss 2.957698
Epoch 2500, Loss 2.933134
Epoch 3000, Loss 2.928648
Epoch 3500, Loss 2.927830
Epoch 4000, Loss 2.927679
Epoch 4500, Loss 2.927652
Epoch 5000, Loss 2.927647


tensor([  5.3671, -17.3012], requires_grad=True)